# Generated by Django 6.0.2 on 2026-02-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('reviews', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
