# Generated by Django 6.0.2 on 2026-02-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Laptops', 'Laptops'), ('Smartphones', 'Smartphones'), ('Audio', 'Audio'), ('Wearables', 'Wearables'), ('Monitores', 'Monitores'), ('Gaming', 'Gaming')], max_length=100),
        ),
    ]
